return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 50,
  tileheight = 50,
  nextlayerid = 4,
  nextobjectid = 12,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "platforms",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = -450,
          y = -50,
          width = 900,
          height = 150,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 328,
          y = -52,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = -100,
          y = -200,
          width = 200,
          height = 150,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "text",
          x = -450,
          y = -450,
          width = 390.036,
          height = 59.5523,
          rotation = 0,
          visible = true,
          text = "Chapter 1",
          fontfamily = "Sans Serif",
          pixelsize = 39,
          wrap = true,
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "text",
          x = 2,
          y = 152,
          width = 210.438,
          height = 40,
          rotation = 0,
          visible = true,
          text = "W or Up Arrow to jump",
          wrap = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "text",
          x = -450,
          y = -300,
          width = 210.438,
          height = 40,
          rotation = 0,
          visible = true,
          text = "The idea of bouncing",
          wrap = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "misc",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "start",
          type = "",
          shape = "point",
          x = 350,
          y = -100,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "goal",
          type = "",
          shape = "point",
          x = -350,
          y = -100,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "next",
          type = "levels.w1l2",
          shape = "point",
          x = 0,
          y = -350,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
